export enum ActionType {

    //music
    PLAY_MUSIC = 'PLAY_MUSIC',
    PAUSE_MUSIC = 'PAUSE_MUSIC',
    PLAY_MUSIC_BATTLE = 'PLAY_MUSIC_BATTLE',
    PAUSE_MUSIC_BATTLE = 'PAUSE_MUSIC_BATTLE',

    //session
    SIGN_IN = 'SIGN_IN',
    SIGN_OUT = 'SIGN_OUT',

    //ranking
    ADD_POKEMON_RANKING = 'ADD_POKEMON_RANKING',
    REMOVE_POKEMON_RANKING = 'REMOVE_POKEMON_RANKING',
    CHANGE_REVIEW = 'CHANGE_REVIEW',
    INITIAL_DB_RANKING = 'INITIAL_DB_RANKING',


    //battle
    I_CHOOSE_YOU = 'I_CHOOSE_YOU',

    THERE_IS_BATTLE = 'THERE_IS_BATTLE',
    NO_BATTLE = 'NO_BATTLE',

    BATTLE_DATA = 'BATTLE_DATA',

    BATTLE_MODE = 'BATTLE_MODE',
    NO_BATTLE_MODE = 'NO_BATTLE_MODE',
}