export enum ActionType {
    PLAY_MUSIC = 'PLAY_MUSIC',
    PAUSE_MUSIC = 'PAUSE_MUSIC',

    SIGN_IN = 'SIGN_IN',
    SIGN_OUT = 'SIGN_OUT',

    ADD_POKEMON_RANKING = 'ADD_POKEMON_RANKING',
    REMOVE_POKEMON_RANKING = 'REMOVE_POKEMON_RANKING',
    CHANGE_REVIEW = 'CHANGE_REVIEW',
    INITIAL_DB_RANKING = 'INITIAL_DB_RANKING',

    I_CHOOSE_YOU = 'I_CHOOSE_YOU',

    THERE_IS_BATTLE = 'THERE_IS_BATTLE',
    NO_BATTLE = 'NO_BATTLE',

    PLAY_MUSIC_BATTLE = 'PLAY_MUSIC_BATTLE',
    PAUSE_MUSIC_BATTLE = 'PAUSE_MUSIC_BATTLE',

    BATTLE_WON = 'BATTLE_WON',
    BATTLE_LOST = 'BATTLE_LOST',
    BATTLE_COMPLETED = 'BATTLE_COMPLETED',
    BATTLE_ABANDONED = 'BATTLE_ABANDONED',
    BATTLE_POINTS = 'BATTLE_POINTS',
    BATTLE_POKEMON_SPOTTED = 'BATTLE_POKEMON_SPOTTED',
}